name = "PiccoloPlots"
uuid = "f42a522c-b487-4f73-ad5a-ad0c3e4a12c8"
version = "0.4.0"
authors = ["Aaron Trowbridge <aaron.j.trowbridge@gmail.com> and contributors"]

[deps]
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
NamedTrajectories = "538bc3a1-5ab9-4fc3-b776-35ca1e893e08"
PiccoloQuantumObjects = "5a402ddf-f93c-42eb-975e-5582dcda653d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[weakdeps]
QuantumToolbox = "6c2fb7c5-b903-41d2-bc5e-5a7c320b9fab"

[extensions]
MakieAnimationsExt = ["Makie"]
QuantumToolboxExt = ["QuantumToolbox", "Makie"]

[compat]
CairoMakie = "0.13, 0.14, 0.15"
LaTeXStrings = "1.4"
LinearAlgebra = "1.10, 1.11, 1.12"
Makie = "0.24"
NamedTrajectories = "0.8"
PiccoloQuantumObjects = "0.8"
QuantumToolbox = "0.40"
Random = "1.10, 1.11, 1.12"
Reexport = "1.2"
TestItemRunner = "1.1"
TestItems = "1.0"
julia = "1.10, 1.11, 1.12"

[extras]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
QuantumToolbox = "6c2fb7c5-b903-41d2-bc5e-5a7c320b9fab"

[targets]
test = ["Test", "CairoMakie", "QuantumToolbox"]
